### ISSUE TITLE
Slow tick speed issue

### ISSUE THREAD

**Issue by LoneZHero** [SamLam140330/DangerousWorld#12]
Hello SamLam,
I have really been enjoying your modpack and have already played 100+ hours on that world. But for some reason it started lagging more and more over the course of 2-4 hours until its absolutely unplayable (not FPSrate, but tick rate). I tried going back to when it started and doing none of the stuff that i had been doing until then, but the lag still keeps on increasing.
I dont really know what i can do anymore and i really want to continue playing, so i linked debug report, a backup from before it began and a save where it has already become unplayable. I could also mention that I worked with Thaumcraft and Mekanism when it started.

[profile-results-2022-04-19_21.48.03.txt](https://github.com/SamLam140330/DangerousWorld/files/8530020/profile-results-2022-04-19_21.48.03.txt)
https://www.dropbox.com/scl/fo/7f4q4kq6g4pg5e1er4m4i/h?dl=0&rlkey=99w1h41pdk1jcu5pdmcuwfixu

Greetings,
LoneZHero

**Comment by SamLam140330** [comment]
Hello LoneZHero,

Thank you so much for enjoying my Modpack
Received the problem. I will download the world and see where the problem is as soon as possible

Regards,
Sam Lam

**Comment by SamLam140330** [comment]
Hello LoneZHero,

I have tried to join the world to profile it but I don't see any critical reason that makes the tick(TPS) drop
Could you please try the below methods to see if they can solve the problem?

1. Make sure that you are using the latest version of Java 8 as it has fixed some security issues and GC collection which may increase the FPS
2. Make sure that you have given the game at least 6GB of ram. 8GB of ram would be better
![2](https://user-images.githubusercontent.com/48656764/164994000-8a0b6da3-c924-4d24-b292-a855fd016b70.jpg)

3. Could you also try to install Optifine and adjust some settings based on your computer specification? Due to the license, I can't directly put the mod into the Modpack so you need to install it by yourself. Basically, just drag and drop the mod to your "mods" folder

I have updated your world to version 1.3 which has fixed one known performance issue. You can download it here: https://www.dropbox.com/s/r1ffd08q711dres/Break%20the%20Isle.zip?dl=1

Version 1.3 also comes with a mod called lag goggles, which can help you indicate the machine that causes your server lag. (You might need to change the key binding to use it)

> * Please note that version 1.3 removed the Electroblob's Wizardry mod. If you have played before, some related items will be removed
> * Please also note that version 1.3 required Forge version 1.12.2 - 14.23.5.2859 or above. If you are not using it, please also update your Forge version
![1](https://user-images.githubusercontent.com/48656764/164994055-3dbcedec-7943-4786-a6de-53c20bce0e7d.jpg)

Useful link:
Java 8 download link: https://www.java.com/zh-TW/download/manual.jsp
Optifine download link: https://optifine.net/downloads
Forge download link: https://files.minecraftforge.net/net/minecraftforge/forge/index_1.12.2.html

I hope the above information can help you, feel free to content me if you have any questions. Enjoy the Dangerous World :)

Regards,
Sam Lam

**Comment by LoneZHero** [comment]
Hello Sam Lam,

Thank you so much! I will try using optic one as soon as possible and check my Java and forge versions. I use 12GB RAM for the modpack, so it really shouldn’t be an issue (everytime I checked it’s well below 100% usage) 

However I am not sure if this will resolve the issue, since it randomly started after 100+ hours playtime and it’s keeps happening  when I load a backup from when it started. I will keep you updated on the things you suggested me to try.

Regards,
LoneZHero
